name: A11y test
on: 
  push:
    paths-ignore:
      - 'reports/**'
    branches:
      - gh-pages

jobs:
  build-deploy:
    name: A11y test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Install pa11y
        run: npm install -g pa11y-ci pa11y-ci-reporter-html
      - name: run pa11y test
        run: pa11y-ci --sitemap https://cds-snc.github.io/${{ github.event.repository.name }}/sitemap.xml
      - name: Commit
        if: always()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "A11y report"
      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@29f05e01bb17e6f28228b47437e03a7b69e1f9ef
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: 'gh-pages' 
