name: A11y test
on:
  push:
    paths-ignore:
      - 'reports/**'
    branches:
      - gh-pages

jobs:
  build-deploy:
    name: A11y test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install pa11y
        run: npm install -g pa11y-ci pa11y-ci-reporter-html
      - name: run pa11y test
        run: pa11y-ci --sitemap https://cds-snc.github.io/${{ github.event.repository.name }}/sitemap.xml
      - name: Commit
        if: always()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "A11y report"
      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@c8e916676288f4db183792490450557e2d4296ef
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: 'gh-pages'
