name: Eleventy Build
on: 
  push:
    paths-ignore:
      - README.md
    branches:
      - main

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
        env:
          PATH_PREFIX: ${{ github.event.repository.name }}
          GITHUB_ORG: cds-snc
      - name: Add a11y action
        run: |
          mkdir -p ./_site/.github/workflows/
          cp -r ./.github/workflows/a11y-tests.yaml ./_site/.github/workflows/a11y-tests.yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935 # v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.ACCESS_TOKEN }}
          exclude_assets: 'admin/index.html,admin/config.yml'
