name: Eleventy Build
on:
  push:
    paths-ignore:
      - README.md
    branches:
      - main

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
        env:
          PATH_PREFIX: ${{ github.event.repository.name }}
          GITHUB_ORG: cds-snc
      - name: Add a11y action
        run: |
          mkdir -p ./_site/.github/workflows/
          cp -r ./.github/workflows/a11y-tests.yaml ./_site/.github/workflows/a11y-tests.yaml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.ACCESS_TOKEN }}
          exclude_assets: 'admin/index.html,admin/config.yml'
